title: Open Source Software Quiz

defaults:
  maxTimeSeconds: 60
  pointsToGain: 1
 teams:
  - name: Master
    password: lohith123
    isMaster: true

rounds:
  - name: Open Source Basics
    questions:
      - question: What does the term "open source" mean?
        choices: [Freely available code, Free to use, Requires a license fee, Only for Linux]
        answer: Freely available code

      - question: Which of the following is an open source operating system?
        choices: [Windows, macOS, Ubuntu, iOS]
        answer: Ubuntu

      - question: What license is commonly used in open source projects?
        choices: [GPL, EULA, NDA, TOS]
        answer: GPL

  - name: Famous Open Source Projects
    questions:
      - question: Who founded the Free Software Foundation (FSF)?
        choices: [Bill Gates, Steve Jobs, Linus Torvalds, Richard Stallman]
        answer: Richard Stallman

      - question: What is Git primarily used for?
        choices: [Designing websites, Writing documents, Source code version control, Compiling programs]
        answer: Source code version control

      - question: Which company owns GitHub?
        choices: [Google, Microsoft, IBM, Red Hat]
        answer: Microsoft

  - name: OSE Fun
    questions:
      - question: Where is KL University located?
        choices: [Hyderabad, Vijayawada, Chennai, Bengaluru]
        answer: Vijayawada

      - question: How much would you rate the class of OSE?
        choices: [1, 2, 3, 4, 5]
        answer: 5

      - question: How much are you interested in attending the morning OSE class?
        choices: [excited, too much, boring, interested]
        answer: excited

