name: Build and tests
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Downgrade NPM version
      uses: actions/setup-node@v2
      with:
        node-version: '8'
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
    - name: Setup sbt launcher
      uses: sbt/setup-sbt@v1
    - name: Build and Test
      run: sbt -v +test
